use_frameworks!

platform :ios, '10.0'

target 'ios_mobimap_module_flutter_Example' do
  pod 'ios_mobimap_module_flutter', :path => '../'

  target 'ios_mobimap_module_flutter_Tests' do
    inherit! :search_paths

    
  end
end
